name: CI
on:
  push:
    paths:
      - "**.js"
      - "**.ts"
      - "**.yml"
      - "**.json"
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Verify MySQL connection from container
        run: |
          apt-get update
          apt-get install -y mysql-client
          mysql --host mysql -uroot -proot -e "SHOW DATABASES"

      - name: Setup NodeJS
        uses: actions/setup-node@v1

      - name: Setup Yarn
        run: |
          npm install -g yarn

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test --watchAll=false
        env:
          JWT_TOKEN: secret
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: dev
