name: CI
on:
  push:
    paths:
      - "**.js"
      - "**.ts"
      - "**.yml"
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: "dev"
          mysql root password: ${{ secrets.MySqlRootPassword }}
          mysql user: "dev"
          mysql password: "dev"
      - name: Test
        run: yarn test --watchAll=false
        env:
          JWT_TOKEN: secret
          MYSQL_USER: root
          MYSQL_PASSWORD: ${{ secrets.MySqlRootPassword }}
          MYSQL_DATABASE: dev
